from app import app

print(" CCCC  OOO  N   N N   N EEEEE  CCCC TTTTT")
print("C     O   O NN  N NN  N E     C       T  ")
print("C     O + O N N N N N N EEEE  C       T  ")
print("C     O   O N  NN N  NN E     C       T  ")
print(" CCCC  OOO  N   N N   N EEEEE  CCCC   T  ")
print()
print("TTTTT H   H EEEEE      ")
print("  T   H   H E       +  ")
print("  T   HHHHH EEEE   +++ ")
print("  T   H   H E       +  ")
print("  T   H   H EEEEE      ")
print()
print("PPPP  Y   Y TTTTT H   H  OOO  NN  N IIIII  SSSS TTTTT  AAA   SSSS")
print("P   P  Y Y    T   H   H O   O N N N   I   S       T   A   A S    ")
print("PPPP    Y     T   HHHHH O + O N N N   I    SSS    T   AAAAA  SSS ")
print("P       Y     T   H   H O   O N N N   I       S   T   A   A     S")
print("P       Y     T   H   H  OOO  N  NN IIIII SSSS    T   A   A SSSS ")
